### ISSUE TITLE
Boot container

### ISSUE THREAD

**Issue by jbdelhommeau** [jderusse/docker-dns-gen#1]
Hello,
I installed this container and it works fine ! Thank you for that.
But now, I want launch automatically this container when host system boot. Do you have a solution or tips ?

**Comment by jderusse** [comment]
Great idea. I've always been too lazy to search how to starts containers on boot.
Thank you for creating this issue, I discover that it was really easy. See my PR :)

**Comment by jbdelhommeau** [comment]
Thank you very much for this solution.
It's easy and it's work well !

**Comment by gitoverflow** [comment]
Could i also use docker compose to launch it ? 

I just tried this configuration, but it doesn't work:

`  dns-gen:
    image: jderusse/dns-gen
    ports:
        - 53:53
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock`
