### ISSUE TITLE
[SOLVED] My containers are not resolving domains

### ISSUE THREAD

**Issue by Shubhankitmishra** [jderusse/docker-dns-gen#21]
After using dns-gen i was able to access my containers through container.docker . But i realised that i can't ping to www.google.com from my container then i pinged to google's ip
![download](https://user-images.githubusercontent.com/36031123/43564891-34d7d35e-9646-11e8-8382-1249ef3ffd08.png)
 and yes getting response. so i stopped dns-gen container and checked and now my containers are resolving domains (able to ping www.google.com).

**Comment by B-Galati** [comment]
Is dnsmasq configured as mentioned in the doc ?

**Comment by Shubhankitmishra** [comment]
Yes, I think Dnsmasq is configured and working fine.

**Comment by Shubhankitmishra** [comment]
Actually on which pc this problem is occurring on that pc dnsmasq is configured. To debug this problem I installed docker on another pc and pulled httpd image and started dns-gen. But on this pc i am able to ping www.google.com while using dns-gen. I am confused that what the issue is.
![image](https://user-images.githubusercontent.com/36031123/43574131-023ceffe-9661-11e8-99f9-be27e061a264.png)

**Comment by jderusse** [comment]
can you check the `/etc/resolv.conf` in the container ? it should be `nameserver 172.17.42.1` (or the IP of docker0 => use `sudo ifconfig docker0` to check it)

**Comment by Shubhankitmishra** [comment]
yes my docker0 ip is 192.168.0.1 and, My /etc/resolve.conf is
nameserver 192.168.0.1

**Comment by jderusse** [comment]
do you have the dnsmasq running on your host? use `sudo netstat -ntlp` et look for sometgin listening on port 53

**Comment by Shubhankitmishra** [comment]
here is the output of the command:-

![image](https://user-images.githubusercontent.com/36031123/43641684-3ce1f500-9742-11e8-9544-7db823f8ea1f.png)

**Comment by Shubhankitmishra** [comment]
I fixed it by adding this `{
	"dns": ["8.8.8.8", "8.8.4.4"]
}` in 
`/etc/docker/daemon.json`

![image](https://user-images.githubusercontent.com/36031123/43642113-d78392d4-9743-11e8-87e8-8363d4f157c7.png)

**Comment by Shubhankitmishra** [comment]
Thanks for your help.

**Comment by B-Galati** [comment]
I am sorry but it's not the right solution :/

Containers will just use an external DNS you provided in docker config 
It will not use your local DNS from your host. It could be quite annoying in some situations like when you are connected to a VPN.

Something is misconfigured with your dsn-gen container.
It should be bind to local port 54 not 53. I guess your local dsnmasq is not running.
On my computer I have:

```
51c14b73b27f        jderusse/dns-gen    "entrypoint -R"          7 months ago        Up 5 days           0.0.0.0:54->53/udp       dns-gen
```

Please double check README carefully. Everything is explained.

**Comment by Shubhankitmishra** [comment]
I am connected to a vpn and not facing any problem. Because the dns i gived in config file is the same dns that i am using locally. After trying many methods this approach is working fine for me.

**Comment by sashaaro** [comment]
Probably related to https://github.com/docker/libnetwork/issues/2187#issuecomment-403372190

**Comment by Shubhankitmishra** [comment]
> Probably related to [docker/libnetwork#2187 (comment)](https://github.com/docker/libnetwork/issues/2187#issuecomment-403372190)

yes.
