### ISSUE TITLE
Docker container failure in dns configuration with Ubuntu 20.04

### ISSUE THREAD

**Issue by Aakash2** [jderusse/docker-dns-gen#29]
Hi @jderusse,
I am looking for help in running dns-gen container in Ubuntu 20.04 OS as detailed below:

_docker images | grep dns_
jderusse/dns-gen      latest    66c9f77b33ec   6 weeks ago    16.9MB

When the container is up and running logs show below msg :

Received event start for container 6dfc415dbde3
2022/11/09 20:17:51 Generated '/etc/dnsmasq.conf' from 2 containers
2022/11/09 20:17:51 Running 'dnsmasq-reload -u root '
2022/11/09 20:17:51 Error running notify command: dnsmasq-reload -u root , exit status 2
2022/11/09 20:17:51 Contents of /etc/dnsmasq.conf did not change. Skipping notification 'dnsmasq-reload -u root '
chroot: can't change root directory to '/host': No such file or directory
sed: /host: No such file or directory

Any clue about the root cause or a work around to fix this?

Akash

**Comment by alquerci** [comment]
Hello @Aakash2,

I have the issue, I dig deeper on it and found why.

In next minutes I will create a PR with a patch.

**Comment by Aakash2** [comment]
Thank you @alquerci
