### ISSUE TITLE
Container stops working

### ISSUE THREAD

**Issue by j3j5** [jderusse/docker-dns-gen#31]
Hi, I'm using this and for some reason, every now and then, the container stops listening on port 53 and I have to restart it to make it work. Checking the container logs, I see a message being output every second or so that reads
```
sed: no previous regexp
```

Any idea what could it be or how to fix it?

Thanks!

**Comment by alquerci** [comment]
Hello @j3j5 

It depends on how you started dns-gen.

My hypothesis
- The environment variable `GATEWAY` is empty.
    - It explains the complaint of `sed`.
    - look at the [Manual install](https://github.com/jderusse/docker-dns-gen#manual-install) for details
- Maybe related to #30
