### ISSUE TITLE
seems, but this solution not working after update docker to 1.10.3 on ubuntu 14.10

### ISSUE THREAD

**Issue by galillei** [jderusse/docker-dns-gen#8]

**Comment by sanuter** [comment]
Replace 172.17.42.1 on 172.17.0.1

**Comment by fspegni** [comment]
I had a similar problem when using docker-dns-gen with ansible < 2.2.0. In my case it was not a docker-dns-gen problem, and the solution was to upgrade ansible to 2.2.0 (or more). 

PS
this was the bug causing me troubles: https://github.com/ansible/ansible/issues/17495
